import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cm
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();        
        
        CURDLayout obcurd = new CURDLayout();        
        try{

             obcurd.conn = (Connection) DriverManager.getConnection(obcurd.DB_URL_TABLE, obcurd.USER, obcurd.PASS);
             if(obcurd.conn != null){

                     System.out.println("Database is connected for creating table");
                     DefaultTableModel model = (DefaultTableModel) jTable_Edit.getModel();
                     PreparedStatement stmt=obcurd.conn.prepareStatement("select * from registration");
                     ResultSet rs=stmt.executeQuery();
                     while(rs.next()){
                        model.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3)});
                     }

             }
             else{
                     System.out.println("unable to create database connection");
             }       
        }catch(SQLException se){
           //Handle errors for JDBC
           se.printStackTrace();
        }catch(Exception e){
           //Handle errors for Class.forName
           e.printStackTrace();
        }finally{
           //finally block used to close resources
           try{
              if(obcurd.stmt!=null)
                 obcurd.conn.close();
           }catch(SQLException se){
           }// do nothing
           try{
              if(obcurd.conn!=null)
                 obcurd.conn.close();
           }catch(SQLException se){
              se.printStackTrace();
           }//end finally try
        }//end try
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_SearchField = new javax.swing.JTextField();
        jButton_SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Edit = new javax.swing.JTable();
        jTextField_EditId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_EditName = new javax.swing.JTextField();
        jTextField_EditAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Edit");

        jButton_SearchButton.setText("Search");
        jButton_SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchButtonActionPerformed(evt);
            }
        });

        jTable_Edit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address"
            }
        ));
        jTable_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_EditMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Edit);

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        jLabel4.setText("Address");

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Update)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_SearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_SearchButton))
                                    .addComponent(jTextField_EditId)
                                    .addComponent(jTextField_EditName)
                                    .addComponent(jTextField_EditAddress))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SearchButton)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_EditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_EditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_EditAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Update))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchButtonActionPerformed
        CURDLayout obcurd = new CURDLayout();
        try{

             obcurd.conn = (Connection) DriverManager.getConnection(obcurd.DB_URL_TABLE, obcurd.USER, obcurd.PASS);
             if(obcurd.conn != null){
                     PreparedStatement stmt=obcurd.conn.prepareStatement("select * from registration where id=?");
                     stmt.setInt(1,Integer.parseInt(jTextField_SearchField.getText()));
                     ResultSet rs=stmt.executeQuery();
                     while(rs.next()){
                        jTextField_EditId.setText(String.valueOf(rs.getInt(1)));
                        jTextField_EditName.setText(rs.getString(2));
                        jTextField_EditAddress.setText(rs.getString(3));
                     }

             }
             else{
                     System.out.println("unable to create database connection");
             }       
        }catch(SQLException se){
           //Handle errors for JDBC
           se.printStackTrace();
        }catch(Exception e){
           //Handle errors for Class.forName
           e.printStackTrace();
        }finally{
           //finally block used to close resources
           try{
              if(obcurd.stmt!=null)
                 obcurd.conn.close();
           }catch(SQLException se){
           }// do nothing
           try{
              if(obcurd.conn!=null)
                 obcurd.conn.close();
           }catch(SQLException se){
              se.printStackTrace();
           }//end finally try
        }//end try
    }//GEN-LAST:event_jButton_SearchButtonActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        CURDLayout obcurd = new CURDLayout();
        try{

             obcurd.conn = (Connection) DriverManager.getConnection(obcurd.DB_URL_TABLE, obcurd.USER, obcurd.PASS);
             if(obcurd.conn != null){                    

                    PreparedStatement stmt=obcurd.conn.prepareStatement("update registration set Name=? , Address=?  where id=?");
                    stmt.setString(1,jTextField_EditName.getText());
                    stmt.setString(2,jTextField_EditAddress.getText());
                    stmt.setInt(3,Integer.parseInt(jTextField_EditId.getText()));

                    int i=stmt.executeUpdate();
                    System.out.println(i+" records updated");
                 
                 
                    DefaultTableModel model = (DefaultTableModel) jTable_Edit.getModel();
                    
                    while(model.getRowCount()>0)
                    {
                       model.removeRow(0);
                    }
             }
             else{
                     System.out.println("unable to create database connection");
             }       
        }catch(SQLException se){
           //Handle errors for JDBC
           se.printStackTrace();
        }catch(Exception e){
           //Handle errors for Class.forName
           e.printStackTrace();
        }finally{
           //finally block used to close resources
           try{
              if(obcurd.stmt!=null)
                 obcurd.conn.close();
           }catch(SQLException se){
           }// do nothing
           try{
              if(obcurd.conn!=null)
                 obcurd.conn.close();
           }catch(SQLException se){
              se.printStackTrace();
           }//end finally try
        }//end try
        
        obcurd = new CURDLayout();        
        try{

             obcurd.conn = (Connection) DriverManager.getConnection(obcurd.DB_URL_TABLE, obcurd.USER, obcurd.PASS);
             if(obcurd.conn != null){

                     System.out.println("Database is connected for creating table");
                     DefaultTableModel model = (DefaultTableModel) jTable_Edit.getModel();
                     PreparedStatement stmt=obcurd.conn.prepareStatement("select * from registration");
                     ResultSet rs=stmt.executeQuery();
                     while(rs.next()){
                        model.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3)});
                     }

             }
             else{
                     System.out.println("unable to create database connection");
             }       
        }catch(SQLException se){
           //Handle errors for JDBC
           se.printStackTrace();
        }catch(Exception e){
           //Handle errors for Class.forName
           e.printStackTrace();
        }finally{
           //finally block used to close resources
           try{
              if(obcurd.stmt!=null)
                 obcurd.conn.close();
           }catch(SQLException se){
           }// do nothing
           try{
              if(obcurd.conn!=null)
                 obcurd.conn.close();
           }catch(SQLException se){
              se.printStackTrace();
           }//end finally try
        }//end try
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jTable_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_EditMouseClicked
        int i = jTable_Edit.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_Edit.getModel();
        jTextField_EditId.setText(model.getValueAt(i,0).toString());
        jTextField_EditName.setText(model.getValueAt(i,1).toString());
        jTextField_EditAddress.setText(model.getValueAt(i,2).toString());
    }//GEN-LAST:event_jTable_EditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SearchButton;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Edit;
    private javax.swing.JTextField jTextField_EditAddress;
    private javax.swing.JTextField jTextField_EditId;
    private javax.swing.JTextField jTextField_EditName;
    private javax.swing.JTextField jTextField_SearchField;
    // End of variables declaration//GEN-END:variables
}
